apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: 'Flowsource'
  description: 'Cognizant flowsource plugin developer - OJT Evalution'
  annotations:
    flowsource/github-workflows: 'run-since-updater' # use this instead

spec:
  type: website
  lifecycle: experimental
  owner: Mahima
